Wwwision:
  GraphQL:
    endpoints:
      'graphql':
        schema: 'resource://ByTorsten.GraphQLTest/Private/GraphQL/schema.graphql'
        resolverPathPattern: 'ByTorsten\GraphQLTest\Resolver\{Type}Resolver'
#        resolvers:
#          'Query': 'ByTorsten\Test\Resolver\QueryResolver'
#          'Vehicle': 'ByTorsten\Test\Resolver\VehicleResolver'
Neos:
  Flow:
    mvc:
      routes:
        'Wwwision.GraphQL':
          variables:
            'endpoint': 'graphql'
